#!/bin/sh
# backup by cloning
# create clone with 'cd /Volumes/Elvis/backups/cdh; git clone --mirror ~/git/cdh/hive'
BACKUP_HOME=/Volumes/Elvis/backups
for repoName in cdh/hive.git \
		cdh/hive2.git \
		cdh/hive3.git \
		cdh/hive-iml.git \
		asf/hive.git  \
		asf/hive2.git  \
		asf/hive-iml.git \
		scripts.git \
		cdh/hive2-iml.git
do
	repos=${BACKUP_HOME}/$repoName
	echo $repos
	cd $repos
	git remote update
	git gc --auto
 	echo '------------------------'
done


