#!/usr/bin/env bash
#
if $(id -G | grep -qE '\<(114|544)\>')
then
	echo "running as admin"
else
	echo "not admin"
	exit 1
fi
SOURCE_VOL=elvis
SOURCE_DRIVE=f
BACKUP_VOL=genesis
BACKUP_DRIVE=g


cd /cygdrive
b_str=$(cat $BACKUP_DRIVE/VOLUME.txt)
s_str=$(cat $SOURCE_DRIVE/VOLUME.txt)
if [  "$s_str" != ${SOURCE_VOL} ]; then
    	echo "/cygdrive/$SOURCE_DRIVE is not ${SOURCE_VOL} volume, is $s_str"
	exit 1
else
	echo found ${SOURCE_VOL}
fi
if [  "$b_str" != ${BACKUP_VOL} ]; then
    	echo "/cygdrive/$BACKUP_DRIVE is not ${BACKUP_VOL} volume, is $b_str"
	exit 1
else
	echo found ${BACKUP_VOL}
fi

RSYNC_CMD='rsync -av --delete   --no-owner --no-group --ignore-errors'


# copy Elvis completely
echo "backup dvd"
${RSYNC_CMD} ${SOURCE_DRIVE}/dvd ${BACKUP_DRIVE}/from_elvis/Elvis | delete_dir_lines_from_rsync echo "backup docs"
${RSYNC_CMD} ${SOURCE_DRIVE}/docs ${BACKUP_DRIVE}/from_elvis/Elvis | delete_dir_lines_from_rsync
echo "backup the from_home dir"
${RSYNC_CMD} ${SOURCE_DRIVE}/from_home ${BACKUP_DRIVE}/from_elvis/Elvis | delete_dir_lines_from_rsync
echo "backup itunes"
${RSYNC_CMD} ${SOURCE_DRIVE}/itunes ${BACKUP_DRIVE}/from_elvis/Elvis | delete_dir_lines_from_rsync
echo "backup everything"
${RSYNC_CMD} ${SOURCE_DRIVE} ${BACKUP_DRIVE}/from_elvis | delete_dir_lines_from_rsync
