#!/usr/bin/env bash
#
BACKUP_VOL=Clash
SOURCE_VOL=Elvis
cd /Volumes
if [ ! -d ${BACKUP_VOL} ]; then
    echo Could not find ${BACKUP_VOL} volume
	exit 1
else
	echo found ${BACKUP_VOL}
fi
# copy from home
rsync -av --delete --ignore-errors --modify-window=5 ${BACKUP_VOL}/backup ${SOURCE_VOL}/from_home
# copy itunes back
rsync -av --delete --ignore-errors --modify-window=5 ${SOURCE_VOL}/itunes ${BACKUP_VOL}/andrew_itunes
