#!/usr/bin/env bash
#
SOURCE_VOL=Elvis
BACKUP_VOL=Gaga
cd /Volumes
if [ ! -d ${BACKUP_VOL} ]; then
	echo Could not find ${BACKUP_VOL} volume
	exit 1
else
	echo found ${BACKUP_VOL}
fi
rsync -av --delete --ignore-errors ${SOURCE_VOL} ${BACKUP_VOL}/back
