#!/usr/bin/env bash
#
SOURCE_VOL=Elvis
BACKUP_VOL=Gaga
cd /Volumes
if [ ! -d ${SOURCE_VOL} ]; then
	echo Could not find ${SOURCE_VOL} volume
	exit 1
else
	echo found ${SOURCE_VOL}
fi
if [ ! -d ${BACKUP_VOL} ]; then
	echo Could not find ${BACKUP_VOL} volume
	exit 1
else
	echo found ${BACKUP_VOL}
fi
rsync -av --delete --ignore-errors ${SOURCE_VOL} ${BACKUP_VOL}/back

rsync -av --delete --ignore-errors ~/Incoming ${BACKUP_VOL}/back
rsync -av --delete --ignore-errors ~/Documents ${BACKUP_VOL}/back
rsync -av --delete --ignore-errors ~/docs ${BACKUP_VOL}/back


echo any music in the wrong place?
gfind '/Users/asherman/Music/iTunes/iTunes Media/Music'
echo would be listed above
