#!/usr/bin/env bash
#
#
# https://superuser.com/questions/660191/how-to-check-if-cygwin-mintty-bash-is-run-as-administrator
if $(id -G | grep -qE '\<(114|544)\>')
then
	echo "running as admin"
else
	echo "not admin"
	exit 1
fi
SOURCE_VOL=elvis
SOURCE_DRIVE=f
BACKUP_VOL=clash
BACKUP_DRIVE=g
cd /cygdrive
g_str=$(cat $BACKUP_DRIVE/VOLUME.txt)
f_str=$(cat $SOURCE_DRIVE/VOLUME.txt)
if [  "$f_str" != ${SOURCE_VOL} ]; then
    	echo "/cygdrive/$SOURCE_DRIVE is not ${SOURCE_VOL} volume, is $f_str"
	exit 1
else
	echo found ${SOURCE_VOL}
fi
if [  "$g_str" != ${BACKUP_VOL} ]; then
    	echo "/cygdrive/$BACKUP_DRIVE is not ${BACKUP_VOL} volume, is $g_str"
	exit 1
else
	echo found ${BACKUP_VOL}
fi
# copy from home (CLash) to Elvis
rsync --dry-run -av --delete --ignore-errors  ${BACKUP_DRIVE}/backup ${SOURCE_DRIVE}/from_home
exit
