#!/bin/sh
# backup by cloning
# create clone with 'cd /Volumes/Elvis/backups/cdh; git clone --mirror ~/git/cdh/hive'
#
# try 'git config gc.auto 256' to force more packing 
# see https://stackoverflow.com/questions/16337498/understanding-git-gc-auto
#

# where backups are stored
BACKUP_HOME=/Volumes/Elvis/backups
REPO_NAMES=(cdh/hive.git  cdh/hive2.git  cdh/hive3.git  cdh/hive-iml.git  asf/hive.git   asf/hive2.git   asf/hive-iml.git  scripts.git  cdh/hive2-iml.git)
for repoName in "${REPO_NAMES[@]}"
do
	repos=${BACKUP_HOME}/$repoName
	echo $repos
	cd $repos
	git remote update
	git gc --auto
 	echo '------------------------'
done


