#!/usr/bin/env bash
# For branches of the form xxxx_dd checkout a branch of the form xxxx_dd++

set -e

BRANCH=`git rev-parse --abbrev-ref HEAD`

echo current branch is $BRANCH

PARSED_BRANCH=`echo $BRANCH | sed 's/\(.*\)_\(\d*\)/\1 \2/'`
PREFIX=`echo ${PARSED_BRANCH} | awk '{print $1}'`
SUFFIX=`echo ${PARSED_BRANCH} | awk '{print $2}'`

# echo prefix = $PREFIX
# echo suffix = $SUFFIX

if [ -z "$SUFFIX" ]
then
    echo no suffix
    exit 1
fi

if [ "$SUFFIX" -ne "$SUFFIX" ] 2>/dev/null
then
    echo "$SUFFIX is not an integer !!"
    exit 1
fi

NEW_SUFFIX=`expr $SUFFIX + 1`

# echo NEW = $NEW
NEW_BRANCH=${PREFIX}_${NEW_SUFFIX}
echo new branch = ${NEW_BRANCH}

git checkout -b ${NEW_BRANCH}

