#!/usr/bin/env bash
#
# login to c1c shell pod

# find the fe with the tenant
fe=$(c1c-get-frontend)

# find the ip address of the coordinator
ip=$(kubectl get pods -n $fe -o wide | grep coordinator | awk '{print $6}')
echo "Access shell with:"
echo "impala-shell --protocol='hs2-http' -i ${ip}:28000"
kubectl exec --stdin --tty impala-shell -n c1c-services -- /bin/bash
