#!/usr/bin/env bash
#
MACHINE=Genesis
SOURCE=/media/asherman/$MACHINE/from_elvis/Elvis/itunes/Music
MOVIES=/media/asherman/$MACHINE/from_elvis/Elvis/dvd/Movies

echo "copying music"
rsync -av --delete --ignore-errors  ${SOURCE} /Andrew

echo "copying movies"
rsync -av --delete --ignore-errors  ${MOVIES} /Andrew
