#!/usr/bin/env bash
# copy dropbox files
MAC="asherman-MBP"
ANDREW="andrew-desktop"
if [[ ${HOSTNAME} != ${MAC}* && ${HOSTNAME} != "${ANDREW}" ]];then
	echo you are on the wrong machine, you should be on ${MAC} or ${ANDREW}
	exit 1
fi

OPTIONS2="--info=progress2"

if [[ ${HOSTNAME} == ${MAC}*  ]];then
    OPTIONS2=""
fi

# --bwlimit=50 takes 50 out of 346.24kB/s at home
OPTIONS="--bwlimit=50"

while getopts f opts; do
   case ${opts} in
        f)
            OPTIONS=""
            ;;
        *)
            echo "usage: $0 [-f]"
            echo "[-f] means no throttling"
            exit 0
            ;;
   esac
done

rsync $OPTIONS $OPTIONS2 -rv --delete --update -e ssh asherman-desktop.sf.cloudera.com:Dropbox ~

rsync -rv --delete --update -e ssh ~/BackDropbox asherman-desktop.sf.cloudera.com:BackDropBox.${HOSTNAME}

