#!/usr/bin/env bash
arr=("$@")

for item in "${arr[@]}";
do
    tokenUri="https://auth.docker.io/token"
    data=("service=registry.docker.io" "scope=repository:$item:pull")
    token="$(curl --silent --get --data-urlencode ${data[0]} --data-urlencode ${data[1]} $tokenUri | jq --raw-output '.token')"
    # echo token=$token
    listUri="https://index.docker.io/v2/$item/tags/list"
    authz="Authorization: Bearer $token"
    curl  --get -H "Accept: application/json" -H "Authorization: Bearer $token" $listUri
    result="$(curl --silent --get -H "Accept: application/json" -H "Authorization: Bearer $token" $listUri | jq --raw-output '.')"
done
