#!/bin/bash
# print out current branches
#

GIT_HOME=~/git

# set SRC_REPOS to a list of repositories to to look at
SRC_REPOS=( \
    asf/Impala \
    asf/Impala2 \
    asf/Impala3 \
    cdh/Impala \
    )

for repoName in "${SRC_REPOS[@]}"
do
	repos=${GIT_HOME}/$repoName
	echo
	echo In $repos
	cd $repos
	git status --untracked-files=no
 	echo '------------------------'
done


