#!/bin/bash
# print out current branches
#

GIT_HOME=~/git

# set SRC_REPOS to a list of repositories to to look at
SRC_REPOS=( \
    go/src/github.com/hortonworks/edws \
    go4/src/github.com/hortonworks/edws/ \
    go5/src/github.com/hortonworks/edws/ \
    go6/src/github.com/hortonworks/edws/ \
    )

for repoName in "${SRC_REPOS[@]}"
do
	repos=${GIT_HOME}/$repoName
	echo
	echo In $repos
	cd $repos
	git status --untracked-files=no
 	echo '------------------------'
done


