#!/bin/bash
#
# classpath to paste into clion project file
# CLASSPATH=`echo_classpath` ./be/build/debug/util/metrics-test
CP2=$(echo_classpath | sed "s?${IMPALA_HOME}?\$PROJECT_DIR\$?g" )
echo '        <env name="CLASSPATH" value="'$CP2'" />'



