#! /usr/bin/env python
import urllib, json
url = "https://layer.bicyclesharing.net/map/v1/fgb/map-inventory"
response = urllib.urlopen(url)
data = json.loads(response.read())
features = data["features"]
for x in features:
  if 'properties' in x:
    properties = x['properties']
    if 'station' in properties:
      station = properties['station']
      station_name = station['name']
      bikes_available = station['bikes_available']
      docks_available = station['docks_available']
      if 'Gennessee' in station_name:
        print ("{:2d} of {:2d} at {}".format(bikes_available, bikes_available + docks_available, station_name))

