#! /usr/bin/env python
import urllib, json
url = "https://layer.bicyclesharing.net/map/v1/fgb/map-inventory"
response = urllib.urlopen(url)
data = json.loads(response.read())
print data
features = data["features"]
print features
for x in features:
  print x['properties']['station']['name']
