#!/bin/sh
# where is my code, I mean it this time
# You screwed up, so search for code in backups
#

if [ "$#" -ne 1 ]
then
	echo "usage: $0 pattern"
	exit 1;
fi

BACKUP_HOME=/Volumes/Elvis/backups

# list of repos to to look at
# list of repos to backup
REPO_NAMES=( \
    asf/hadoop.git  \
    asf/hive-iml.git \
    asf/hive.git  \
    asf/hive2.git  \
    cdh/asherman-jenkins-master.git \
    cdh/hadoop.git \
    cdh/hive-iml.git \
    cdh/hive.git \
    cdh/hive2-iml.git \
    cdh/hive2.git \
    cdh/hive3.git \
    jdbc.git \
    kitchen/cloudcat-hive-ptest.git \
    kitchen/cloudstack-reporting.git \
    scripts.git \
    ssh.git \
    starship/cmf.git \
    )


for repoName in "${REPO_NAMES[@]}"
do
	repos=${BACKUP_HOME}/$repoName
	# echo $repos
	cd $repos
	git branch | egrep -i "$1" && echo "found in $repos\n"

 	# echo '------------------------'
done


