#!/bin/sh
# where is my code?
# find repo with branch matching parameter
#

if [ "$#" -ne 1 ]
then
	echo "usage: $0 pattern"
	exit 1;
fi

GIT_HOME=~/git

# set SRC_REPOS to a list of repositories to to look at
. $(dirname "$0")/src_repos.sh

for repoName in "${SRC_REPOS[@]}"
do
	repos=${GIT_HOME}/$repoName
	# echo $repos
	cd $repos
	git branch | egrep -i "$1" && echo "found in $repos\n"

 	# echo '------------------------'
done


