#!/bin/sh
# where is my code?
# print out some recent branches
#

GIT_HOME=~/git

# set SRC_REPOS to a list of repositories to to look at
. $(dirname "$0")/src_repos.sh

for repoName in "${SRC_REPOS[@]}"
do
	repos=${GIT_HOME}/$repoName
	echo
	echo In $repos
	cd $repos
	show_branches -4
 	echo '------------------------'
done


