#!/bin/sh
# where is my code, I mean it this time
# You screwed up, so search for code in backups
#

if [ "$#" -ne 1 ]
then
	echo "usage: $0 pattern"
	exit 1;
fi

BACKUP_HOME=/Volumes/Elvis/backups

# set REPO_NAMES to a list of repositories to to look at
. $(dirname "$0")/repos.sh


for repoName in "${REPO_NAMES[@]}"
do
	repos=${BACKUP_HOME}/$repoName
	# echo $repos
	cd $repos
	git branch | egrep -i "$1" && echo "found in $repos\n"

 	# echo '------------------------'
done


