#!/usr/bin/env bash
# format raw div table
#
# to get data:
# select some of the table, then right click->view selection source
# when source opens in new tab, use control-A to select whole line and copy-paste

sed 's?</div></div>?\n?g' |\
sed 's?<div class="grid-container">??g' |\
sed 's?<div class="grid-row grid-column green-bg" role="presentation">??g' |\
sed 's?<div class="grid-row grid-column white-bg" role="presentation">??g' |\
sed 's?<div class="grid-row grid-column yellow-bg" role="presentation">??g' |\
sed 's?,?\\,?g' |\
sed 's?</span></div><div?,?g' |\
sed 's?<div class="grid-cell"><span role="presentation" class="">??g' |\
sed 's?class="grid-cell"><span role="presentation" class="link bold">??g' |\
sed 's?class="grid-cell"><span role="presentation" class="link">??g' |\
sed 's?class="grid-cell"><span role="presentation" class="link" data-ui-id=".*" aria-describedby="">??g' |\
sed 's?class="grid-cell"><span role="presentation" class="link bold" data-ui-id=".*" aria-describedby="">??g' |\
sed 's?class="link" data-ui-id=".*" aria-describedby="">??g' |\
sed 's?class="grid-cell"><span role="presentation" class="link calloutTrigger" data-ui-id=".*" aria-describedby="" aria-expanded="false">??g' |\
sed 's?class="grid-cell"><span role="presentation" class="">??g' |\
sed 's?</span>??g' |\
sed 's?</div><div class="grid-cell">?,?g' |\
sed 's?<div class="grid-row"><div class="grid-cell">??g' |\
sed 's?</div>??g'



# sed 's?</div><div class="grid-cell">?XX?g'
