#!/usr/bin/env bash
# format raw div table
#
# to get data:
# select some of the table, then right click->view selection source
# when source opens in new tab, use control-A to select whole line and copy-paste

xmllint --format - |\
grep -v '<div class="grid-cell">$' |\
sed 's?<div.*">??' |\
sed 's?^ *??' |\
grep -v '^</div>' |
grep -v ^$ |\
grep -v '<?xml version="1.0"?>' |\
#sed 's?,?","?g' |\
sed 's?</div>??g' |\
sed 's?</span>??g' |\
sed 's?.*>??g' |\
awk '{
val=$0
printf "\"%s\"%s",val,NR%32?",":"\n" ;
}'

