#!/usr/bin/env bash
# format cut and paste of ancestry data
# https://unix.stackexchange.com/questions/155709/use-sed-or-awk-to-move-rows-to-columns

# Assume 43 columns
awk '{
printf "%s%s",$0,NR%43?",":"\n" ;
}'
