#!/usr/bin/env bash
# format cut and paste of ancestry data
# https://unix.stackexchange.com/questions/155709/use-sed-or-awk-to-move-rows-to-columns

# Assume 43 columns
while read line
do
  # Escape any commas
  echo $line | sed 's/,/\\,/g'
done | awk '{
val=$0
printf "%s%s",val,NR%43?",":"\n" ;
}'
