#!/usr/bin/env bash
#
# get the namespace of the latest coordinator
#
K8S_NAMESPACE=$(kubectl get pods -A --sort-by=.metadata.creationTimestamp  | \
    grep Running | grep coordinator | awk '{print $1}' | tail -1)
echo ${K8S_NAMESPACE}

