#!/bin/bash
username=$1
if [ "${username}" != "" ]; then
    response=$(curl  --silent "https://github.com/signup_check/username" \
        --header "Host: github.com" \
        --header "Origin: https://github.com" \
        --header "X-Requested-With: XMLHttpRequest" \
        --referer "https://github.com/" \
        --user-agent "Mozilla/5.0 AppleWebKit/537.36" \
        --data "value=${username}")
    if [ "${response}" == "" ] || [ "${response}" == " " ]; then
        echo -e "\e[0;92mOk.\e[0m Username ${username} available."
    else
        response=$(echo $response | sed "s/Username /Username '$username' /g")
        echo -e "\e[0;91mError.\e[0m ${response}"
    fi
else
    echo "Usage: ${0} cixtor"
fi

