#!/usr/bin/env bash
#
# Run k9s on the most recent warehouse
#
K8S_NAMESPACE=$(kubectl get pods -A --sort-by=.metadata.creationTimestamp  | \
    grep Running | grep coordinator | awk '{print $1}' | tail -1)
if [[ ! ${K8S_NAMESPACE} ]]; then
    echo "Did not find running coordinator in k8s."
    exit 1
fi
k9s -n ${K8S_NAMESPACE}

