#! /bin/bash
# log ip
IPFILE=/home/asherman/Dropbox/tmp/lastip
IPBAK=/home/asherman/Dropbox/tmp/lastip.prev
IPLOG=/home/asherman/tmp/lastip.log
IP=`ifconfig enp0s31f6  | grep 'inet addr' | awk '{print $2}' | awk -F: '{print $2}'`
OLDIP=`cat $IPFILE`
date >> $IPLOG
if [ "$IP" = "$OLDIP" ]; then
  echo "same ip $OLDIP" >> $IPLOG
else
  echo "new ip $IP replaces $OLDIP" >> $IPLOG
  mv $IPFILE $IPBAK
  echo $IP > $IPFILE
fi


