#!/bin/sh
# backup by cloning
BTMP=/tmp/gback$$.txt
# create clone with 'cd cdh; git clone --mirror ~/git/cdh/hive'
for repoName in cdh/hive.git cdh/hive-iml.git asf/hive.git asf/hive-iml.git
do
	repos=/Volumes/Elvis/backups/$repoName
	echo $repos
	cd $repos
	git remote update
	git gc --auto
 	echo '------------------------'
done


