#! /bin/sh
if [ "$#" -lt 1 ]
then
	echo "usage: $0 file [driver (defaults to TestCliDriver)]"
	exit 1
elif [ "$#" -eq 2 ]
then
    DRIVER=$2
else
    DRIVER=TestCliDriver
fi
echo DRIVER=${DRIVER}
AFILE=$1
echo file = ${AFILE}
if [ ! -f "${AFILE}" ]
then
    echo cannot find ${AFILE}
    exit 1
fi
LIST=`fgrep .${DRIVER}. ${AFILE} | sed 's?.*\[??' | sed 's?\].*?.q,?' | sed 's/ *(.*)//g' | tr -d "\n" `
echo mvn test -Dtest.output.overwrite=true  -Dtest=${DRIVER} -Dqfile=${LIST} -Pitests
echo mvn test  -s gbn-m2-settings.xml -Dtest.output.overwrite=true  -Dtest=${DRIVER} -Dqfile=${LIST} -Pitests

# example data
#
# org.apache.hadoop.hive.cli.TestSparkCliDriver.testCliDriver[union_remove_15]
# org.apache.hadoop.hive.cli.TestSparkCliDriver.testCliDriver[union_remove_18]
# org.apache.hadoop.hive.cli.TestSparkCliDriver.testCliDriver[union_remove_17]
# org.apache.hadoop.hive.cli.TestSparkCliDriver.testCliDriver[union_remove_16]
# org.apache.hadoop.hive.cli.TestSparkCliDriver.testCliDriver[union_remove_25]
# org.apache.hadoop.hive.cli.TestMiniSparkOnYarnCliDriver.testCliDriver[orc_merge2]
# org.apache.hadoop.hive.cli.TestCliDriver.testCliDriver[vector_partitioned_date_time]
# org.apache.hadoop.hive.cli.TestCliDriver.testCliDriver[orc_int_type_promotion]

