#!/usr/bin/env bash

DRIVER_ARRAY=()
if [ "$#" -lt 1 ]
then
	echo "usage: $0 [-a] file [driver (defaults to TestCliDriver, use -a for all)]"
	exit 1
fi

INTEST_FILE=$1
TEST_FILE=~/tmp/TEST_$$
if [ ! -f "${INTEST_FILE}" ]
then
    echo cannot find ${INTEST_FILE}
    exit 1
fi

grep -v ^# $INTEST_FILE > $TEST_FILE

if [ "$#" -eq 2 ]
then
    if [[ $2 == -a ]]
    then
        # bash 4 only syntax
        # https://stackoverflow.com/questions/971162/how-to-initialize-a-bash-array-with-output-piped-from-another-command
        readarray -t DRIVER_ARRAY < <(cat ${TEST_FILE} | awk -F\[ '{print $1}' | sed '/^\s*$/d' | sort -u | awk -F. '{print $6}')
	    # echo use all drivers
    else
        DRIVER_ARRAY+=($2)
    fi
else
    DRIVER_ARRAY+=(TestCliDriver)
fi

echo upstream:
for DRIVER in "${DRIVER_ARRAY[@]}"
do
	# echo driver from array is $DRIVER
	LIST=`fgrep .${DRIVER}. ${TEST_FILE} | sed 's?.*\[??' | sed 's?\].*?.q,?' | sed 's/ *(.*)//g' | tr -d "\n" `
    echo mvn test -Dtest.output.overwrite=true  -Dtest=${DRIVER} -Dqfile=${LIST} 
done

echo
echo

echo downstream:
for DRIVER in "${DRIVER_ARRAY[@]}"
do
	# echo driver from array is $DRIVER
	LIST=`fgrep .${DRIVER}. ${TEST_FILE} | sed 's?.*\[??' | sed 's?\].*?.q,?' | sed 's/ *(.*)//g' | tr -d "\n" `
    echo mvn test  -s gbn-m2-settings.xml -Dtest.output.overwrite=true  -Dtest=${DRIVER} -Dqfile=${LIST} 
done






# example data
#
# org.apache.hadoop.hive.cli.TestSparkCliDriver.testCliDriver[union_remove_15]
# org.apache.hadoop.hive.cli.TestSparkCliDriver.testCliDriver[union_remove_18]
# org.apache.hadoop.hive.cli.TestSparkCliDriver.testCliDriver[union_remove_17]
# org.apache.hadoop.hive.cli.TestSparkCliDriver.testCliDriver[union_remove_16]
# org.apache.hadoop.hive.cli.TestSparkCliDriver.testCliDriver[union_remove_25]
# org.apache.hadoop.hive.cli.TestMiniSparkOnYarnCliDriver.testCliDriver[orc_merge2]
# org.apache.hadoop.hive.cli.TestCliDriver.testCliDriver[vector_partitioned_date_time]
# org.apache.hadoop.hive.cli.TestCliDriver.testCliDriver[orc_int_type_promotion]

