#!/bin/sh
# backup by cloning

for repos in /cygdrive/e/backups/emcapms2_backup_clone /cygdrive/e/backups/emcapms_backup_clone
do
	echo $repos
	cd $repos
	git fetch --all
	# https://stackoverflow.com/questions/10312521/how-to-fetch-all-git-branches
        for remote in `git branch -r | grep -v HEAD`; 
        do 
                git branch --track ${remote#origin/} $remote; 
        done
	git --no-pager log --all -1
	git gc --auto
 	echo '------------------------'
done


