#!/usr/bin/env python3
# https://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk, Gdk
print(*Gtk.Clipboard.get(Gdk.atom_intern("CLIPBOARD", True)).wait_for_targets()[1], sep = "\n")
