#!/bin/sh
#
# List the most recently used branches
# https://stackoverflow.com/questions/5188320/how-can-i-get-a-list-of-git-branches-ordered-by-most-recent-commit

if [ "$#" -eq 1 ]
then
    if [[ $1 == -* ]] 
    then
        AANEW=`echo "$1" | cut -c2-`
    else
        AANEW=$1
    fi
    if [ "$AANEW" -eq "$AANEW" ] 2>/dev/null
    then
        # echo "$AANEW is an integer !!"
        # number of branches to show
        AANUM=$AANEW
    else	
	echo "parameter '$AANEW' is not an integer"
	echo "usage: $0 [numberOfBranches]"
	exit 1
    fi
else
 # default is 10
 AANUM=10
fi

git for-each-ref --count=$AANUM --sort=-committerdate refs/heads/ --format='%(refname:short)'
