#!/usr/bin/env bash
#
# Copy music from andrew-desktop to a flash drive
#
ANDREW="andrew-desktop"
TMP1=/tmp/synca$$
if [[ ${HOSTNAME} != ${ANDREW} ]];then
	echo you are on the wrong machine, you should be on ${ANDREW}
	exit 1
fi
SOURCE_VOL=~/Music
BACKUP_VOL=/media/asherman/KINGSTON

if [ ! -d ${BACKUP_VOL} ]; then
	echo Could not find ${BACKUP_VOL} volume
	exit 1
else
	echo found ${BACKUP_VOL}
fi

# # cd $SOURCE_VOL
# find . -type f -print0 | while IFS= read -r -d $'\0' file; 
	# mv "$file" "${file}.bak"
	# name=$(echo $file | sed 's/://g' | sed 's/?//g')
	# cp "${file}.bak" "$name"
# done



rsync -av --delete --no-owner --no-group ${SOURCE_VOL} ${BACKUP_VOL}
