#!/usr/bin/env bash

# tunnel to impala coordinator webui
    
NS="--all-namespaces"
if [ "$#" -eq 1 ]
then
  echo "using ns $1"
  NS="-n $1"
fi

mapfile -t pods < <(kubectl  get pods ${NS} | grep  coordinator | grep Running | grep 5/5)


if [ ${#pods[@]} -eq 1 ]; 
then 
  echo was one coordinator
elif [ ${#pods[@]} -eq 0 ]; 
then
  echo no running coordinators
  exit 1
else
  echo too many coordinators in k8s
  exit 1
fi

namespace=$(echo ${pods[0]} | awk '{print $1}')
# echo namespace=$namespace
name=$(echo ${pods[0]} | awk '{print $2}')
# echo name=$name

# target port
target=25013

kubectl port-forward --address localhost,127.0.0.1 $name -n $namespace ${target}:25000 &
echo "browse to http://localhost:${target}"


