#!/usr/bin/env bash

# tunnel to impala hs2 webui
    
NS="--all-namespaces"
if [ "$#" -eq 1 ]
then
  echo "using ns $1"
  NS="-n $1"
fi

mapfile -t pods < <(kubectl  get pods ${NS} | grep  hiveserver2-0 | grep Running)


if [ ${#pods[@]} -eq 1 ]; 
then 
  echo was one hs2
elif [ ${#pods[@]} -eq 0 ]; 
then
  echo no running hs2s
  exit 1
else
  echo too many hs2s in k8s
  exit 1
fi

if [ "$#" -eq 1 ]
then
  namespace=$1
  # echo namespace=$namespace
  name=$(echo ${pods[0]} | awk '{print $1}')
  # echo name=$name
else
  namespace=$(echo ${pods[0]} | awk '{print $1}')
  # echo namespace=$namespace
  name=$(echo ${pods[0]} | awk '{print $2}')
  # echo name=$name
fi


# target port
target=35000

echo "browse to http://localhost:${target}/metric"
kubectl port-forward --address localhost,127.0.0.1 $name -n $namespace ${target}:${target}



