#!/usr/bin/env bash
cd ~/git/cdh/hive-iml
AAHIVE=/Users/asherman/git/cdh/hive/packaging/target/apache-hive-1.1.0-cdh5.13.0-SNAPSHOT-bin/apache-hive-1.1.0-cdh5.13.0-SNAPSHOT-bin 
if [ ! -d  $AAHIVE ]; then
	echo cannot find $AAHIVE
	exit 1;
fi
cp hive-site.xml $AAHIVE/conf
cp  hive-log4j.properties ../hive/service/target/classes
cp hive-env.sh $AAHIVE/conf
cd $AAHIVE/bin
echo '(rm -f option to readlink)'
sleep 2
vi ./hive
./schematool -dbType derby -initSchema

