#!/usr/bin/env bash
set -e
AAIML=~/git/asf/hive-iml
AAHIVE_VERS=3.0.0
AADEV=`pwd`
# AACDH_VERS=cdh6.x
# note apache has no cdh
AAHIVE=${AADEV}/packaging/target/apache-hive-${AAHIVE_VERS}-SNAPSHOT-bin/apache-hive-${AAHIVE_VERS}-SNAPSHOT-bin 
AAGIT=`pwd`
if [ ! -d  $AAHIVE ]; then
	echo cannot find $AAHIVE
	exit 1;
fi
# cd ${AAIML}
cp ${AAIML}/hive-site.xml $AAHIVE/conf
cp ${AAIML}/hive-log4j.properties ${AADEV}/common/target/classes
# sed "s?XXXX?${AAGIT}?"  < hive-env.sh > $AAHIVE/conf/hive-env.sh
cd $AAHIVE/bin
echo '(rm -f option to readlink)'
sleep 2
vi ./hive
./schematool -dbType derby -initSchema

