#!/usr/bin/env bash
# convert the .xlsx files to csv, and convert csv values to rows
for input in $(ls *.xlsx)
do
	basename=$(echo $input | sed 's/.xlsx//')
	# sssconvert can deduce exporter from suffix but force it to csv
	ssconvert --export-type=Gnumeric_stf:stf_csv $input ${basename}.tmp
	# convert csv row into simple list
	sed 's/, /\n/g' < ${basename}.tmp | tr -d \" | sed 's/ $//' > ${basename}.csv
done

